version: "3"
services:
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: '$$Test%Password'
            ACCEPT_EULA: "Y"
    