version: "3"
services:
    # web:
    #     build: .
    #     ports:
    #         - "80:80"
    #     depends_on:
    #         - db
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: '$$Test%Password'
            ACCEPT_EULA: "Y"
    